config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'admin', to: 'paintings#index'
  resources :paintings, only:[:create, :update, :destroy]
  resources :themes, only:[:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :theme
  has_one_attached :photo

  validates :name, :theme, :photo, :year, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :paintings

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @themes = Theme.all.sort_by(&:name)
    @paintings = Painting.all
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @themes = Theme.all.sort_by(&:name)
    @paintings = Painting.all

    @painting = Painting.new
    @theme = Theme.new
  end

  def create
    @painting = Painting.new(painting_params)
    @painting.theme = Theme.find(painting_params[:theme_id])

    # binding.pry
    # source_data = File.read(@painting.photo.key)
    # @painting.photo = Tinify.from_buffer(source_data).to_buffer
    # source = Tinify.from_file(@painting.photo)
    # source.to_file(@painting.photo)

    if @painting.save
      redirect_to admin_path
    else
      @add_error = true
      @themes = Theme.all
      render 'paintings/index', data: { remote: true, toggle: "modal", target: "#paintingModal" }
    end
  end

  def update
    @painting = Painting.find(params[:id])
    @painting.update(painting_params)
    redirect_to admin_path
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to admin_path
  end

  private

  def painting_params
    params.require(:painting).permit(:name, :year, :dimensions, :theme_id, :number, :sold, :description, :photo)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def create
    @theme = Theme.new(theme_params)

    if @theme.save
      redirect_to admin_path
    else
      @add_error = true
      @paintings = Painting.all
      render 'paintings/index'
    end
  end

  def update
    @theme = Theme.find(params[:id])
    @theme.update(theme_params)
    redirect_to admin_path
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to admin_path
  end

  private

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tag_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon-32x32.png') %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<div class="paintings">

  <div class="banner">
    <% @paintings.shuffle.first(20).each do |painting| %>
      <%= cl_image_tag painting.photo.key,
        class: "painting-thumbnail",
        crop: :thumb,
        style: "
          top: #{rand(200)}px;
          left: #{rand(800)}px;
          "
        %>

    <% end %>
    <h1 class="main-title">Bienvenue chez Kty </h1>
  </div>

  <% @themes.each do |theme|  %>
    <% next if theme.paintings.empty? %>
    <div class="theme">
      <div class="container">
        <h4 class="category title active-title">
          <%= theme.name %>
        </h4>
        <div class="slider container">
          <button class="arrow prev button-hidden">&#8592;</button>
          <div class="slider-cards">
            <% theme.paintings.sort_by(&:year).reverse.each do |painting| %>
              <div class="card-painting">
                <%= cl_image_tag painting.photo.key, class: "framed-painting", "data-index" => painting.id %>
                <p>
                  <%= painting.name %>
                </p>
                <p>
                  <%= painting.dimensions %>
                </p>
              </div>
            <% end %>
          </div>
          <button class="arrow next button-hidden">&#8594;</button>
        </div>
      </div>

    </div>

  <% end %>
</div>

<!-- Hidden zoom div waiting for a click on paintings -->
<% @paintings.each do |painting| %>
  <div class="zoomDiv" id="zoom-<%= painting.id %>">
    <div class="details">
      <h5 class="title">
        <%= painting.name %>
      </h5>
      <p><%= painting.year %></p>
      <p><%= painting.dimensions %></p>
      <br>
      <p><%= painting.description %></p>
    </div>
  </div>

<% end %>

<!-- Profile page -->
<div class="profile container d-none">
  <h1>Cathy Schwartz</h1>
  <%= image_tag 'photo_dort.jpg' %>
  <p>
    Passionnée et créative (peinture sur soie, couture...), Kty s'est initié en 2001 à la peinture à l'huile avec Jacques Malenfant, qui tenait  un atelier à Lesmenils.
    <br>Elle a ensuite suivi des cours plus assidus avec Aimé Schlosser à Bayonville, puis chez Abi Gül à Augny.
  </p>
  <a href="mailto: contact@la-galerie-de-kty.art" class=btn>Contact</a>
</div>

<!-- Footer -->
<div class="footer">
  <p>
    Site construit avec <i class="fas fa-heart"></i> par
    <a href="https://remjpn.github.io/profile/" target="_blank">Rémi Schwartz</a>
  </p>
</div>

app/views/paintings/index.html.erb
<div class="paintings">

  <div class="menu">
    <%= link_to "Ajouter", "#paintingModal", "data-toggle" => "modal", id: "add-btn", class: "btn btn-primary" %>
    <%= link_to "Modifier", "#", "data-toggle" => "modal", id: "modify-btn", class: "btn btn-warning btn-disabled" %>
    <%= link_to "Supprimer", "#", method: :delete, data: { confirm: 'Etes-vous sûr(e)?' }, id:"delete-btn", class: "btn btn-danger btn-disabled" %>
  </div>

  <% @themes.each do |theme|  %>
    <%# next if theme.paintings.empty? %>

    <div class="container admin-theme">
      <div class="d-flex theme-bar">
        <h4 class="category title active-title">
          <%= theme.name %>
        </h4>
        <div class="update-theme d-none">
          <%= simple_form_for theme do |f| %>
            <%= f.input :name, label: false %>
          <% end %>
        </div>
        <h4 class="category icons">
          <i class="fas fa-pencil-alt mr-2 icon"></i>

          <% if theme.paintings.empty? %>
            <%= link_to theme_path(theme), method: :delete, data: { confirm: 'Vous êtes sûr?' } do %>
              <i class="far fa-trash-alt mr-3 icon"></i>
            <% end %>
          <% end %>

        </h4>

      </div>
      <div class="">
        <% theme.paintings.sort_by(&:year).reverse.each do |painting| %>
          <%= cl_image_tag painting.photo.key, class: "square-painting", "data-index" => painting.id %>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

<div class="add-themes">
  <hr>
  <br>
  <p>Ajouter un thème: </p>
  <%= simple_form_for @theme do |f| %>
    <%= f.input :name, label: false %>
    <%= f.button :submit, value: 'Ajouter', class: "btn btn-primary" %>
  <% end %>
</div>


<!-- Add a painting -->
<%= render partial:'shared/modal_painting', locals: {painting: @painting} %>

<!-- Modify painting -->
<% @paintings.each do |painting| %>
  <%= render partial:'shared/modal_painting', locals: {painting: painting}  %>
<% end %>

<% if @add_error %>
  <div class="error"></div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal_painting.html.erb
<div class="modal fade" id="paintingModal<%= "-#{painting.id}" if painting.id %>" tabindex="-1" role="dialog" aria-labelledby="paintingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <% if painting.id %>
          <h6 class="modal-title">Modifier le tableau</h6>
        <% else %>
          <h6 class="modal-title">Ajouter un tableau</h6>
        <% end %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for painting do |f| %>
          <div class="d-flex painting-form">
            <div>
              <%= f.input :photo, as: :file %>

            </div>
            <div>
              <%= f.input :name, label: "Titre" %>
              <div class="d-flex align-items-center">
                <%= f.input :year, label: "Année", wrapper_html: { class: "mr-3" }%>
                <%= f.input :dimensions %>
              </div>
              <%= f.association :theme, label: "Thème", collection: @themes %>
              <div class="d-flex align-items-end">
                <%= f.input :number, label: "Numéro", wrapper_html: { class: "mr-3" } %>
                <%= f.input :sold, label: "Vendu" %>
              </div>
              <%= f.input :description %>
            </div>
          </div>

          <div class="text-center mt-4">
            <%= f.button :submit, value: 'Enregistrer', class: "btn btn-primary", data: { disable_with: "En cours..." } %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-kty">
  <a class="section-title title active-title" data-menu="paintings">
    Tableaux
  </a>
  <a class="section-title title" data-menu="profile">
    L'Artiste
  </a>
</div>